#!/usr/bin/env python3

import subprocess
import argparse
import string
import os


IMAGE = 'weddinglist'
REPOSITORY = 'weddinglistacr.azurecr.io'


def sh(cmd, ignore_failure=False, **args):
    code = subprocess.call(string.Template(cmd).substitute(args), shell=True)
    if (not ignore_failure) and code:
        exit(code)


def sh_docker(cmd, docker_cmd='', **args):
    sh('docker run --rm -it -v ${PWD}:/work -w /work ' + docker_cmd +
       ' ${IMAGE}' +
       ' env FLASK_APP=wl PYTHONPATH=/work ' +
       cmd,
       IMAGE=IMAGE,
       PWD=os.getcwd(),
       **args)


def build():
    sh('docker build --rm -t ${IMAGE} .', IMAGE=IMAGE)
    sh('docker pull mysql')
    sh('docker pull azuresdk/azure-cli-python')


def run():
    sh_docker('env FLASK_APP=wl FLASK_DEBUG=1 PYTHONPATH=/work'
              ' flask run --host=0.0.0.0',
              docker_cmd='-p 5000:5000')


def execute(command):
    sh_docker(command)


def check():
    sh_docker('pytest')
    sh_docker('flake8')


def push():
    check()
    sh('docker tag ${IMAGE} ${REPOSITORY}/${IMAGE}'
       ' && docker push ${REPOSITORY}/${IMAGE}',
       IMAGE=IMAGE, REPOSITORY=REPOSITORY)


def sql():
    sh('docker rm --force wl-db', ignore_failure=True)
    sh('docker run --detach --name wl-db -e MYSQL_ROOT_PASSWORD=wl.pass mysql')


def sql_repl(production):
    if production:
        host = 'weddinglistdb.mysql.database.azure.com'
        user = os.environ['WEDDING_LIST_DB_USER'] + '@weddinglistdb'
        password = os.environ['WEDDING_LIST_DB_PASSWORD']
    else:
        # Find the local container's IP address
        host = subprocess.check_output(
            'docker inspect wl-db | jq -r .[0].NetworkSettings.IPAddress',
            shell=True
        ).decode('utf-8').strip()
        user = 'root'
        password = 'wl.pass'

    sh('docker run -it --rm mysql'
       ' sh -c \'exec mysql'
       ' -h"${HOST}" -u"${USER}" -p"${PASSWORD}"\'',
       HOST=host, USER=user, PASSWORD=password)


parser = argparse.ArgumentParser(
    description='Run script for development'
)
subparsers = parser.add_subparsers()

p = subparsers.add_parser('build', help='build the image')
p.set_defaults(action=build)

p = subparsers.add_parser('run', help='run the server locally')
p.set_defaults(action=run)

p = subparsers.add_parser('check', help='run code checks')
p.set_defaults(action=check)

p = subparsers.add_parser('push', help='push the current built image')
p.set_defaults(action=push)

p = subparsers.add_parser('sql', help='start a background local sql server')
p.set_defaults(action=sql)

p = subparsers.add_parser('sql-repl', help='connect to a sql server')
p.add_argument('--production', action='store_true',
               help='connect to the production database')
p.set_defaults(action=sql_repl)

p = subparsers.add_parser('x', help='execute a command in docker')
p.add_argument('command', help='command to execute')
p.set_defaults(action=execute)


args = vars(parser.parse_args())
action = args.pop('action')
action(**args)
